package:
  name: stevedore
  version: 1.5.0

build:
  number: 0

source:
  git_tag: 1.5.0
  git_url: https://git.openstack.org/openstack/stevedore

requirements:
  build:
    - python
    - six
    - pbr
  run:
    - python

about:
  home: https://pypi.python.org/pypi/stevedore
