package:
  name: bpython
  version: 0.14.2

source:
  git_rev: 0.14.2-release
  git_url: https://github.com/bpython/bpython.git

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bpython = bpython:main
    #
    # Would create an entry point called bpython that calls bpython.main()

    - bpython = bpython.cli:main
    - bpython-urwid = bpython.urwid:main
    - bpython-gtk = bpython.gtk_:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pygments

  run:
    - python
    - pygments
    - urwid
    - mock
    - requests

test:
  # Python imports
  imports:
    - bpython.test
    - bpython.translations
    - bpython
    - bpdb
    - mock
    - requests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - bpython --help
    - bpython-urwid --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bpython-interpreter.org
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
