package:
  name: gcc
  version: 4.7.4

build:
  number: 1


source:
  fn: gcc-4.7.4.tar.bz2
  url: http://mirrors.concertpass.com/gcc/releases/gcc-4.7.4/gcc-4.7.4.tar.bz2
  md5: 4c696da46297de6ae77a82797d2abe28

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp 5.1.2 5
    - mpfr >=2.3.1
    - mpc >=0.8.0
    - ppl >=0.11,<1
  run:
    - gmp 5.1.2 5
    - mpfr >=2.3.1
    - mpc >=0.8.0
    - ppl >=0.11,<1

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
