package:
  name: dpath
  version: 1.4.1

build:
  number: 0

source:
  git_rev: build,1.4,1
  git_url: https://github.com/akesterson/dpath-python.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://pypi.python.org/pypi/dpath
