package:
  name: haskell-platform
  version: 2013.2.0.0

source:
  fn: haskell-platform-2013.2.0.0.tar.gz
  url: http://www.haskell.org/platform/download/2013.2.0.0/haskell-platform-2013.2.0.0.tar.gz
  sha1: 8669bb5add1826c0523fb130c095fb8bf23a30ce

build:
  number: 0

requirements:
  build:
    - haskell-ghc ==7.6.3
  run:
    - haskell-ghc ==7.6.3

test:
  commands:
    - alex --help
    - cabal --help
    - happy --help
    - ghc --version

about:
  home: http://www.haskell.org/
  license: BSD
  summary: A standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing.
