package:
  name: haskell-platform
  version: 7.10.3

source:
  fn: haskell-platform-7.10.3.tar.gz
  url: http://haskell.org/platform/download/7.10.3/haskell-platform-7.10.3.tar.gz
  sha256: 0b3f0fea3e4b55ef6a195d6c7a9c43c46caac950c241cfbfad63170c5cbeec07

test:
  commands:
    - alex --help
    - cabal --help
    - happy --help

about:
  home: http://www.haskell.org/
  license: BSD
  summary: A standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing.
