package:
  name: pandoc
  version: 1.15.2

source:
  fn:   pandoc-1.15.2-1-amd64.deb                                                         # [linux64]
  url:  https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb  # [linux64]
  md5:  8eedd750b0c6825ceb3f365f54c7e226                                                  # [linux64]
  fn:   pandoc-1.15.2.pkg                                                                 # [osx]
  url:  https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-osx.pkg      # [osx]
  md5:  a24f622d6f6472bd17a09f0c08ccbc48                                                  # [osx]
  fn:   pandoc-1.15.2-windows.msi                                                         # [win]
  url:  https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-windows.msi  # [win]
  md5:  451220f39f44994a41518e8327c79ed2                                                  # [win]

requirements:
  run:
    - gmp               # [linux64]
    - zlib              # [linux64]

test:
  commands:
    - pandoc --help

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL
  summary: Universal markup converter
