package:
    name:       vim
    version:    7.4.1303

source:
    git_url: https://github.com/vim/vim.git
    git_tag: v7.4.1303


#NOTE: I assume gtk2 and libgettext provided by system
requirements:
    build:
        - python
        - perl
    run:
        - python
        - perl

build:
    detect_binary_files_with_prefix: true # [not linux32]
    number: 0

# vim:set ts=8 sw=4 sts=4 tw=78 et:
