package:
    name:       vim
    version:    7.4.453                                 [win]
    version:    7.4.493                                 [not win]

source:
    #fn: vim-7.4.tar.bz2                                 [not win]
    #url: ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2 [not win]
    hg_url: https://vim.googlecode.com/hg/
    hg_tag: v7.4.453                                    [win]
    hg_tag: v7.4.493                                    [not win]

requirements:
    build:
        - python
        - gettext   [not win]
    run:
        - python
        - gettext   [not win]

build:
    number: 1 [win]
    number: 0 [not win]

# vim:set ts=8 sw=4 sts=4 tw=78 et:
