package:
  name: gstreamer
  version: 1.4.5

source:
  fn: gstreamer-1.4.5.tar.xz
  url: http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.4.5.tar.xz
  sha256: 40801aa7f979024526258a0e94707ba42b8ab6f7d2206e56adbc4433155cb0ae

about:
    home: http://gstreamer.freedesktop.org/
    license: LGPL

requirements:
  build:
    - bison
    - flex
    - glib
  
  run:
    - glib

