package:
  name: gdb
  version: 7.9.1

build:
  number: 0


source:
  fn: gdb-7.9.1.tar.xz
  url: http://ftp.gnu.org/gnu/gdb/gdb-7.9.1.tar.xz
  md5: 35374c77a70884eb430c97061053a36e

requirements:
  build:
  - readline
  - python
  - tk
  run:
  - readline
  - python
  - tk

about:
  home: http://www.gnu.org/software/gdb/ 
  summary: GDB, the GNU Project debugger, allows you to see what is going on `inside' another program while it executes -- or what another program was doing at the moment it crashed. 
  license: GPLv2
