package:
  name: ruamel.base
  version: "1.0.0"

source:
  fn: ruamel.base-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/r/ruamel.base/ruamel.base-1.0.0.tar.gz
  md5: 5b2fb0e7df10672eb2a48dc329f770ee
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ruamel.base

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/ruamel/base
  license: MIT License
  summary: 'place for elements common to multiple ruamel packages'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
