package:
  name: robotframework-databaselibrary
  version: !!str 0.7

source:
  git_rev: 0.7
  git_url: https://github.com/franz-see/Robotframework-Database-Library.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - robotframework = robotframework:main
    #
    # Would create an entry point called robotframework that calls robotframework.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - robotframework

  run:
    - python

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://franz-see.github.io/Robotframework-Database-Library
  summary: Database Library provides utilities and an API for Robot Framework

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
