package:
  name: gst-plugins-base
  version: 1.4.5

source:
  fn: gst-plugins-base-1.4.5.tar.xz
  url: http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.4.5.tar.xz
  sha256: 77bd8199e7a312d3d71de9b7ddf761a3b78560a2c2a80829d0815ca39cbd551d

about:
    home: http://gstreamer.freedesktop.org/
    license: LGPL

requirements:
  build:
    - gstreamer
  
  run:
    - gstreamer


