package:
  name: r-essentials
  version: 1.3

build:
  number: 1

requirements:
  # Not really needed, but just to make sure that they are built
  build:
    - r-base >=3.3.0
    - r-recommended >=3.3.0
    - r-ggplot2 >=2.1.0
    - r-plyr >=1.8.3
    - r-reshape2 >=1.4.1
    - r-dplyr >=0.4.3
    - r-tidyr >=0.4.1
    - r-caret >=6.0_68
    - r-randomforest >=4.6_12
    - r-data.table >=1.9.6
    - r-quantmod >=0.4_5
    - r-shiny >=0.13.2
    - r-rmarkdown >=0.9.6
    - r-glmnet >=2.0_5
    - r-jsonlite >=0.9.20
    - r-zoo >=1.7_13
    - r-irkernel >=0.6.1
    - r-rbokeh >=0.4.2
  run:
    - r-base >=3.3.0
    - r-recommended >=3.3.0
    - r-ggplot2 >=2.1.0
    - r-plyr >=1.8.3
    - r-reshape2 >=1.4.1
    - r-dplyr >=0.4.3
    - r-tidyr >=0.4.1
    - r-caret >=6.0_68
    - r-randomforest >=4.6_12
    - r-data.table >=1.9.6
    - r-quantmod >=0.4_5
    - r-shiny >=0.13.2
    - r-rmarkdown >=0.9.6
    - r-glmnet >=2.0_5
    - r-jsonlite >=0.9.20
    - r-zoo >=1.7_13
    - r-irkernel >=0.6.1
    - r-rbokeh >=0.4.2

about:
  summary: "Some essential packages for working with R"
  license_family: Other
