package:
  name: gcc
  version: 4.9.3

source:
  fn: gcc-4.9.3.tar.bz2
  url: http://mirrors.concertpass.com/gcc/releases/gcc-4.9.3/gcc-4.9.3.tar.bz2
  md5: 6f831b4d251872736e8e9cc09746f327

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl 0.12.2
    - cloog 0.18.1
  run:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl 0.12.2
    - cloog 0.18.1

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL
