package:
  name: gperftools
  version: !!str 2.5

source:
  git_rev: gperftools-2.5
  git_url: https://github.com/gperftools/gperftools.git

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - libunwind
  run:
    - libunwind

about:
  home: https://github.com/gperftools/gperftools/wiki
  summary: A collection of a high-performance multi-threaded malloc() implementation, plus some pretty nifty performance analysis tools
  license: BSD
