package:
  name: isl
  version: "0.15"

source:
  fn: isl-0.15.tar.bz2
  url: ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.15.tar.bz2
  md5: 8428efbbc6f6e2810ce5c1ba73ecf98c

build:
  number: 0

requirements:
  build:
    - gmp
  run:
    - gmp

about:
  license: MIT
  summary: "isl is a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints."
