package:
  name: memory_profiler
  version: "0.37"

source:
  fn: memory_profiler-0.37.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.37.tar.gz
  md5: e406d6599557ebf57f1d27ce91539659

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: BSD License
  summary: 'A module for monitoring memory usage of a python program'
