package:
  name: apr
  version: 1.5.2

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    - curl
    - 7za     [win]

about:
  home: http://apr.apache.org/
  license: Apache License 2.0

# vim:set ts=8 sw=2 sts=2 tw=78 et:
