package:
  name: xcb-proto
  version: 1.11

source:
  fn:  xcb-proto-1.11.tar.bz2
  url: http://xcb.freedesktop.org/dist/xcb-proto-1.11.tar.bz2
  md5: 6bf2797445dc6d43e9e4707c082eff9c

requirements:
  build:
    - python

about:
    home: http://xcb.freedesktop.org/
    license: MIT
