package:
  name: rstudio
  version: 0.99.849

source:
  git_url: git://github.com/rstudio/rstudio.git
  git_tag: v0.99.849

# Note, the qt5 must have WebKit included. The 5.5.0 one in spyder-ide channel
# had it in Jan 2016
# Then, I needed to have the mesa-libGL RPMs installed:
#   % yum install mesa-libGL mesa-libGL-devel
requirements:
  build:
    - cmake
    - r
    - qt5
    - boost

  run:
    - r
    - qt5

about:
  license: AGPL
  summary: "RStudio is an integrated development environment (IDE) for R"
  home: http://www.rstudio.com/
