package:
  name: doxypypy
  version: 0.8.8.6

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.

    - doxypypy = doxypypy.doxypypy:main

  number: 0

source:
  git_tag: 399ba2100b5d9c304fc8b118af024218d49b5f73
  git_url: https://github.com/Feneric/doxypypy.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://pypi.python.org/pypi/doxypypy
