package:
  name: cxxtest
  version: "4.4"

source:
  fn: cxxtest-4.4.tar.gz
  url: https://github.com/CxxTest/cxxtest/releases/download/4.4/cxxtest-4.4.tar.gz
  sha256: 1c154fef91c65dbf1cd4519af7ade70a61d85a923b6e0c0b007dc7f4895cf7d8

build:
  number: 0

requirements:
  run:
    - python

test:
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - cxxtestgen --version | fgrep -q "CxxTest version ${PKG_VERSION}."

about:
  home: http://cxxtest.com/
  license: GPL 3
  summary: "CxxTest Unit Testing Framework."
