package:
  name: guile
  version: 2.0.11.177_461b6

build:
  number: 1
  detect_binary_files_with_prefix: true


source:
  fn: guile-2.0.11.177-461b6.tar.xz
  url: http://hydra.nixos.org/build/36631808/download/4/guile-2.0.11.177-461b6.tar.xz
  md5: 5cbd4e6214660f08263a4f856a6693d5

requirements:
  build:
    - libunistring
    - libffi
    - libgc
    - gmp
    #- libiconv
    #- libintl
    #- libltdl
  run:
    - libunistring
    - libffi
    - libgc
    - gmp

about:
  home: https://www.gnu.org/software/guile/
  summary: "Guile is the GNU Ubiquitous Intelligent Language for Extensions, and the official extension language of the GNU project. a.k.a. GNU's scheme implementation"
  license: LGPL3
  license_file: COPYING.LESSER
