package:
  name: jira
  version: !!str 0.43

source:
  git_rev: 0.43
  git_url: https://github.com/pycontribs/jira.git

#build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - requests >=2.6.0
    - requests-oauthlib >=0.3.3
    - requests-kerberos
    - tlslite >=0.4.4
    - six >=1.9.0
    - setuptools >=0.8.0
    - requests-toolbelt
    - ordereddict
  run:
    - python

about:
  home: http://jira.readthedocs.io/en/latest
  summary: This library eases the use of the JIRA REST API from Python and it has been used in production for years.
  license: Atlassian
