package:
  name: r-tictoc
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.0"

source:
  fn: tictoc_1.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/tictoc_1.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/tictoc/tictoc_1.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - export R_HOME=$PREFIX/lib/R # [not win]
    - $R -e "library('tictoc')" # [not win]
    - "\"%R%\" -e \"library('tictoc')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/collectivemedia/tictoc
  license: Apache License (== 2.0) | file LICENSE
  summary: This package provides the timing functions 'tic' and 'toc' that can be nested. One
    can record all timings while a complex script is running, and examine the values
    later. It is also possible to instrument the timing calls with custom callbacks.
    In addition, this package provides class 'Stack', implemented as a vector, and class
    'List', implemented as a list, both of which support operations 'push', 'pop', 'first',
    'last' and 'clear'.

# The original CRAN metadata for this package was:

# Package: tictoc
# Title: Functions for timing R scripts, as well as implementations of Stack and List structures.
# Version: 1.0
# Author: Sergei Izrailev
# Maintainer: Sergei Izrailev <sizrailev@collective.com>
# Description: This package provides the timing functions 'tic' and 'toc' that can be nested. One can record all timings while a complex script is running, and examine the values later. It is also possible to instrument the timing calls with custom callbacks. In addition, this package provides class 'Stack', implemented as a vector, and class 'List', implemented as a list, both of which support operations 'push', 'pop', 'first', 'last' and 'clear'.
# URL: http://github.com/collectivemedia/tictoc
# Depends: R (>= 3.0.3), methods
# License: Apache License (== 2.0) | file LICENSE
# Copyright: Copyright (C) Collective, Inc. | file inst/COPYRIGHTS
# LazyData: true
# Packaged: 2014-06-17 07:24:01 UTC; sizrailev
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-06-17 10:55:40

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
