package:
  name: rpy2
  version: "2.7.4"

source:
  fn: rpy2-2.7.4.tar.gz
  url: https://pypi.python.org/packages/source/r/rpy2/rpy2-2.7.4.tar.gz
  md5: 62e6037388078a3bcf47642771e043ef
#  patches:
   # List any patch files here
   # - fix.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python
    - r
    - setuptools
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six

  run:
    - python
    - r
    - argparse # [py26]
    - singledispatch # [not (py34 or py35)]
    - six

test:
  # Python imports
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

  commands:
    - echo
    # - python -m rpy2.tests

  requires:
    - ipython
    - r-survival
    - r-ggplot2
    - numpy
    - pandas

about:
  home: http://rpy.sourceforge.net
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python interface to the R language (embedded R)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
