package:
  name: boost
  version: 1.49.0

source:
  fn: boost_1_49_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.49.0/boost_1_49_0.tar.bz2

build:
  number: 4

requirements:
  build:
    - python
    - icu               [unix]
    - bzip2             [unix]
    - libpython         [win]
    - gcc 4.7.4         [unix]
    - pyyaml

  run:
    - icu               [unix]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: free peer-reviewed portable C++ source libraries that work well with the C++ Standard Library.

