package:
  name: pygit2
  version: !!str 0.24.0

source:
  git_rev: v0.24.0
  git_url: https://github.com/libgit2/pygit2.git

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - system # [linux]
    - pkgconfig # [linux]
    - python
    - cffi >=1.0
    - six
    - libgit2 >=0.24.0
  run:
    - system # [linux]
    - python
    - cffi >=1.0
    - six
    - libgit2 >=0.24.0

test:
  imports:
    - pygit2

about:
  home: http://www.pygit2.org
  summary: Pygit2 is a set of Python bindings to the libgit2 shared library, libgit2 implements the core of Git.
  license: GPLv2 with linking exception.
