package:
  name: svn
  version: 1.9.3

source:
  fn: subversion-1.9.3.tar.bz2
  url: http://www.trieuvan.com/apache/subversion/subversion-1.9.3.tar.bz2
  sha1: 27e8df191c92095f48314a415194ec37c682cbcf
  patches:
    - py3_compat.patch        [py>30]

build:
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    - apr      1.5.*
    - openssl  1.0.2*
    - python
    - sqlite   3.9.*
    - swig
    - zlib     1.2.*
  run:
    - apr      1.5.*
    - openssl  1.0.2*
    - sqlite   3.9.*
    - zlib     1.2.*

test:
  commands:
    - svn help

about:
  home: https://subversion.apache.org/
  summary: "Apache Subversion (centralized) version control software"
  license: Apache Software License V.2
