package:
  name: gnumake
  version: 4.2

build:
  number: 1
  detect_binary_files_with_prefix: true


source:
  fn: make-4.2.tar.bz2
  url: http://gnu.askapache.com/make/make-4.2.tar.bz2
  md5: 85ad14d08766201ffe71efa866f4fb91

requirements:
  build:
    - guile
  run:
    - guile

about:
  home: https://www.gnu.org/software/make/
  summary: "GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files."
  license: GPL3
  license_file: COPYING
