package:
  name: r-survival
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.38_3"

source:
  fn: survival_2.38-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/survival_2.38-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/survival/survival_2.38-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: cmprsk
requirements:
  build:
    - r-base
    - gcc # [not win]

  run:
    - r
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('survival')" # [not win]
    - "\"%R%\" -e \"library('survival')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: LGPL (>= 2)
  summary: Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier
    and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated
    failure time models.

# The original CRAN metadata for this package was:

# Title: Survival Analysis
# Maintainer: Terry M Therneau <therneau.terry@mayo.edu>
# Priority: recommended
# Package: survival
# Version: 2.38-3
# Depends: R (>= 2.13.0), graphics, stats
# Imports: splines, methods
# Suggests: cmprsk
# LazyData: Yes
# LazyLoad: Yes
# ByteCompile: Yes
# Authors@R: c(person(c("Terry", "M"), "Therneau", email="therneau.terry@mayo.edu", role=c("aut", "cre")), person("Thomas", "Lumley", role=c("ctb", "trl"), comment="original S->R port and maintainer until 2009"))
# Description: Contains the core survival analysis routines, including definition of Surv objects,  Kaplan-Meier and Aalen-Johansen (multi-state) curves, Cox models, and parametric accelerated failure time models.
# License: LGPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2015-07-01 21:33:35 UTC; therneau
# Author: Terry M Therneau [aut, cre], Thomas Lumley [ctb, trl] (original S->R port and maintainer until 2009)
# Repository: CRAN
# Date/Publication: 2015-07-02 08:40:39

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
