package:
  name: hdf4
  version: 4.2.11

source:
  fn: hdf-4.2.11.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.11.tar.bz2
  md5: 192a0320ef06f657523c2efaee0ccdcf
  patches: 
    - max_files.patch
requirements:
  build:
    - python
    - jpeg
    - zlib
  run:
    - python
    - jpeg
    - zlib

about:
  home: http://www.hdfgroup.org
  license: BSD-stype
