package:
  name: r-recommended
  version: 3.3.0

requirements:
  run:
    - r 3.3.0
    - r-boot
    - r-class
    - r-cluster
    - r-codetools
    - r-foreign
    - r-kernsmooth
    - r-lattice
    - r-mass
    - r-matrix
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-rpart
    - r-spatial
    - r-survival
