package:
  name: oniguruma
  version: 5.9.6

source:
  fn: onig-5.9.6.tar.gz
  url: https://github.com/kkos/oniguruma/releases/download/v5.9.6/onig-5.9.6.tar.gz
  md5: d08f10ea5c94919780e6b7bed1ef9830

build:
  number: 0

about:
    home: https://github.com/kkos/oniguruma
    license:  MIT
