package:
  name: r-revohbase
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2011.7_27"

source:


  git_url: https://github.com/RevolutionAnalytics/rhbase
  git_tag: v2011.7-28
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RevoHBase')" # [not win]
    - "\"%R%\" -e \"library('RevoHBase')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: Apache License (== 2.0)
  summary: Functions to create,delete HBase tables and read/write/scan rows from HBase tables

# The original CRAN metadata for this package was:

# Package: RevoHBase
# Type: Package
# Title: R and HBase Connector
# Version: 2011.7-27
# Date: 2011-07-27
# Author: Revolution Analytics
# Depends: R (>= 2.6.0), methods
# Maintainer: Revolution Analytics <support@revolutionanalytics.com>
# Description: Functions to create,delete HBase tables and read/write/scan rows from HBase tables
# License: Apache License (== 2.0)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
