package:
  name: pixman
  version: 0.32.6

source:
  fn: pixman-0.32.6.tar.gz
  url: http://cairographics.org/releases/pixman-0.32.6.tar.gz
  md5: 3a30859719a41bd0f5cccffbfefdd4c2
  patches:
    - no_test.patch      [win]

build:
  features:
    - vc9                [win and py27]
    - vc10               [win and py34]
    - vc14               [win and py35]

about:
  home: http://cgit.freedesktop.org/pixman/
  license: MIT
  summary: A low-level software library for pixel manipulation
