package:
  name: inkscape
  version: 0.91

source:
  fn: Inkscape-0.91-1-win64.7z # [win64]
  url: https://inkscape.org/en/gallery/item/3938/Inkscape-0.91-1-win64.7z # [win64]
  sha1: 724707f66aa48be0a5746d71da5bf328cb2745bf # [win64]

requirements:
  build:
  - 7za

build:
  number: 0

test:
  commands:
    - inkscape --help

about:
  home: https://inkscape.org
  license: GNU General Public License (GPL)
  summary: vector graphics editor
