package:
  name: yt
  version: 3.2.2

source:
  fn: yt-3.2.2.tar.gz
  url: https://pypi.python.org/packages/source/y/yt/yt-3.2.2.tar.gz
  sha1: e9e907dea0124fbb99a0b3291854ae7307b244ad

build:
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools 
    - libpython # [win]
    - mingw # [win]
  run:
    - python
    - numpy
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD
