package:
  name: pyelftools
  version: 0.23

build:
  number: 0

source:
  git_rev: v0.23
  git_url: https://github.com/eliben/pyelftools.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/eliben/pyelftools
